### ISSUE TITLE
UI - android system integration

### ISSUE THREAD

**Issue by jankoscharf** [EVNotify/v3-feedback#2]
**actual behavior**
When I went to "settings" an did an selection from the menu, the android "back" button (triangle) closes the app. 
The "<" button in the header works as expected.

**expected behavior**
android system "back" button should return one level up/back or to the "home" screen as a fallback to the "<" button in the UI header (refer to https://developer.android.com/guide/navigation/principles)

**Comment by GPlay97** [comment]
Fixed
